<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.alilitech</groupId>
    <artifactId>mybatis-jpa-parent</artifactId>
    <packaging>pom</packaging>
    <version>4.0.0</version>

    <modules>
        <module>mybatis-jpa</module>
        <module>mybatis-jpa-spring</module>
        <module>mybatis-jpa-spring-boot-starter</module>
        <module>mybatis-jpa-generator</module>
    </modules>

    <name>mybatis-jpa-parent</name>
    <description>mybatis jpa is an ORM framework based on mybatis.</description>
    <url>http://mybatisjpa.alilitech.com/</url>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Zhou Xiaoxiang</name>
            <email>mozu_2008@163.com</email>
            <organization>none</organization>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:git@github.com:zhouxx/mybatis-jpa-parent.git</connection>
        <developerConnection>scm:git:git@github.com:zhouxx/mybatis-jpa-parent.git</developerConnection>
        <url>git@github.com:zhouxx/mybatis-jpa-parent.git</url>
    </scm>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>
        <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <mybatis.version>3.5.19</mybatis.version>
        <mybatis.spring.version>4.1.0</mybatis.spring.version>
        <mybatis.springboot.version>4.1.0</mybatis.springboot.version>
        <spring.version>7.0.9</spring.version>
        <jakarta-persistence.version>3.2.0</jakarta-persistence.version>
        <spring-boot.version>4.1.1</spring-boot.version>
    </properties>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <activated>dev</activated>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <activated>test</activated>
            </properties>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <activated>prod</activated>
            </properties>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.9.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>ossrh</publishingServerId>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>2.2.1</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <doclint>none</doclint>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>1.5</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
<!--            <distributionManagement>-->
<!--                <snapshotRepository>-->
<!--                    <id>ossrh</id>-->
<!--                    <url>https://ossrh-s01.oss.sonatype.org/content/repositories/snapshots/</url>-->
<!--                </snapshotRepository>-->
<!--                <repository>-->
<!--                    <id>ossrh</id>-->
<!--                    <url>https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/</url>-->
<!--                </repository>-->
<!--            </distributionManagement>-->
        </profile>
    </profiles>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
